---
- hosts: all
  gather_facts: no
  become: yes
  tasks:

    - file:
        path: "{{ pv['spec']['local']['path'] }}"   
        state: directory
        
    - shell: mount -t tmpfs k8_pv "{{ pv['spec']['local']['path'] }}"

#    - name: Mount tmpfs
#      mount:
#        path: "{{ pv['spec']['local']['path'] }}"
#        src: k8_pv
#        fstype: tmpfs
#        state: present


- hosts: master
  gather_facts: no
  tasks:

    - get_url:
        url: https://raw.githubusercontent.com/QCDIS/k8s_playbooks/master/persistent_volume/local/local_storage-class.yaml
        dest: /tmp/local_storage-class.yaml


    - k8s:
        state: present
        src: /tmp/local_storage-class.yaml

    - shell: kubectl get nodes -o=jsonpath='{}' > /tmp/nodes.yaml


    - fetch:
        src: /tmp/nodes.yaml
        dest: /tmp/nodes.yaml
        flat: yes

    - include_vars:
        file: /tmp/nodes.yaml
        name: nodes


    - debug:
        var: nodes

#
#    - copy:
#        content: "{{ pv }}"
#        dest: /tmp/pv.yaml
#
#
#    - k8s:
#        state: present
#        src: /tmp/pv.yaml
#
#    - shell: kubectl get pv -o="jsonpath={}"
#      register: pv_output

