---
---
- hosts: all
  gather_facts: no
  tasks:

    - file:
        path: "{{ pv['spec']['local']['path'] }}"   
        state: directory


- hosts: master
  gather_facts: no
  tasks:

    - get_url:
        url: https://raw.githubusercontent.com/QCDIS/k8s_playbooks/master/persistent_volume/local/local_storage-class.yaml
        dest: /tmp/local_storage-class.yaml


    - k8s:
        state: present
        src: /tmp/local_storage-class.yaml

    - copy:
        content: "{{ pv }}"
        dest: /tmp/pv.yaml


    - k8s:
        state: present
        src: /tmp/pv.yaml

    - shell: kubectl get pv -o="jsonpath={}"
      register: pv_output

