---       
- hosts: master
  gather_facts: no
  vars:
    k8s_state: present
    k8s_namespace: kubernetes-dashboard
    k8s_dashboard_installed: lookup('env', 'k8s_dashboard_installed')
    ansible_python_interpreter: /usr/bin/python3
  tasks:

    - pip:
        name:
          - openshift==0.11.0
          - kubernetes==11.0.0

    - file:
        path: /tmp/metrics_server
        state: directory

#     - get_url:
#         url: https://raw.githubusercontent.com/QCDIS/k8s_playbooks/main/metrics_server/{{item}}
#         dest: /tmp/metrics_server/{{item}}
#       with_items:
#         - aggregated-metrics-reader.yaml
#         - auth-delegator.yaml
#         - auth-reader.yaml
#         - metrics-apiservice.yaml
#         - metrics-server-deployment.yaml
#         - metrics-server-service.yaml
#         - resource-reader.yaml
    - get_url:
        url: https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
        dest: /tmp/metrics_server/components.yaml


    - k8s:
        state: "{{k8s_state}}"
        src: /tmp/metrics_server/components.yaml
#       with_items:
#         - aggregated-metrics-reader.yaml
#         - auth-delegator.yaml
#         - auth-reader.yaml
#         - metrics-apiservice.yaml
#         - metrics-server-deployment.yaml
#         - metrics-server-service.yaml
#         - resource-reader.yaml
