---
# - hosts: localhost
#   gather_facts: no
#   connection: local
#   tasks:
                
#     - file:
#         path: node_ports
#         state: directory


- hosts: master
  gather_facts: no
  tasks:
          
    - file:
        state: absent
        path: /tmp/node_ports/
        
    - file:
        path: /tmp/node_ports/
        state: directory
        
    - include:  get_node_ports.yaml
      vars: 
        k8s_namespace: "{{ item }}"
      with_items:
        - "kubernetes-dashboard"
        - "default"
        
    - shell: jq -r '.results[].item[]' /tmp/node_ports/{{item}}.json >> /tmp/node_ports/all_node_ports_array 
      with_items:
        - "kubernetes-dashboard"
        - "default"
      
    - shell: cat  /tmp/node_ports/all_node_ports_array
      register: node_ports
       
    - debug:
        var: node_ports


#     - fetch:
#         src: /tmp/node_ports/all_node_ports_array.json
#         dest: node_ports/all_node_ports_array.json
#         flat: yes

#     - include_vars:
#         file: node_ports/all_node_ports_array.json
#         name: node_ports

        

#     - name: Get the public IP address of the network.
#       uri:
#         url: https://api.ipify.org?format=json
#         method: Get
#       changed_when: false
#       register: public_ip
#       until: public_ip.status == 200
#       retries: 6
#       delay: 10
      

#     - set_stats:
#         data: 
#           kubernetes:
#             attributes: 
#               service_urls: 
#                 - "https://{{public_ip['json']['ip']}}:{{item.stdout}}"
#       loop: "{{ node_ports.results }}"  
      

#     - set_fact:
#         attributes: 
#           service_urls: 
#           - "https://{{public_ip['json']['ip']}}:{{item}}"
#       loop: "{{ node_ports | dict2items }}"          
          
#     - name: Display the Dictionaries
#       debug: 
#         var: attributes
      

#     - debug:
#         var: item.value[0].item
#       loop: "{{ node_ports | dict2items }}"
  
