---
- hosts: master
  gather_facts: no
  tasks:
  
    - include:  get_node_ports.yaml
      vars: 
        k8s_namespace: "{{ item }}"
      with_items:
        - "kubernetes-dashboard"
        - "default"
        
