---
- hosts: master
  gather_facts: no
  tasks:
  
    - include:  get_node_ports.yaml
      vars: 
        k8s_namespace: "{{ item }}"
      with_items:
        - "kubernetes-dashboard"
        - "default"
        

    - name: Get the public IP address of the network.
      uri:
        url: https://api.ipify.org?format=json
        method: Get
      changed_when: false
      register: public_ip
      until: public_ip.status == 200
      retries: 6
      delay: 10
      

    - set_fact:
        attributes: 
          service_urls: 
          - "https://{{public_ip.ip}}":item.value[0].item
      loop: "{{ node_ports | dict2items }}"          
          
    - name: Display the Dictionaries
      debug: 
        var: attributes
      

#     - debug:
#         var: item.value[0].item
#       loop: "{{ node_ports | dict2items }}"
  
