---
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
                
    - file:
        path: node_ports
        state: directory


- hosts: master
  gather_facts: no
  tasks:
          
    - file:
        state: absent
        path: /tmp/node_ports/
        
    - file:
        path: /tmp/node_ports/
        state: directory
        
    - include:  get_node_ports.yaml
      vars: 
        k8s_namespace: "{{ item }}"
      with_items:
        - "kubernetes-dashboard"
        - "default"
        

    - name: Get the public IP address of the network.
      uri:
        url: https://api.ipify.org?format=json
        method: Get
      changed_when: false
      register: public_ip
      until: public_ip.status == 200
      retries: 6
      delay: 10
        
    - shell: jq -c -r '.results[] | {"url":("https://{{public_ip['json']['ip']}}:"+(.item[]|tostring))}' /tmp/node_ports/{{item}}.json >> /tmp/node_ports/all_node_ports.json 
      with_items:
        - "kubernetes-dashboard"
        - "default"

    - shell: jq -r .url /tmp/node_ports/all_node_ports.json
      register: node_ports
       
    - include: get_dashboard_token.yaml
    - debug: 
        var: k8s_dashboard_token.stdout | replace('token:      ','')

    - set_stats:
        data: 
          kubernetes:
            attributes: 
              service_urls: "{{ node_ports.stdout_lines }}" 
              tokens: "{{ k8s_dashboard_token.stdout }}" 
      
      

#     - set_fact:
#         attributes: 
#           service_urls: 
#           - "https://{{public_ip['json']['ip']}}:{{item}}"
#       loop: "{{ node_ports | dict2items }}"          
          
#     - name: Display the Dictionaries
#       debug: 
#         var: attributes
      

#     - debug:
#         var: item.value[0].item
#       loop: "{{ node_ports | dict2items }}"
  
