---
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - file:
        path: node_ports
        state: directory

- hosts: master
  gather_facts: no
  tasks:
  
    - file:
        path: /tmp/node_ports/
        state: directory
  
    - include:  get_node_ports.yaml
      vars: 
        k8s_namespace: "{{ item }}"
      with_items:
        - "kubernetes-dashboard"
        - "default"

    - fetch:
        src: /tmp/node_ports/{{item}}
        dest: node_ports
        flat: yes
      with_items:
        - "kubernetes-dashboard"
        - "default"

    - include_vars:
        dir: node_ports
        name: node_ports


    - debug:
        var: node_ports
        

#     - name: Get the public IP address of the network.
#       uri:
#         url: https://api.ipify.org?format=json
#         method: Get
#       changed_when: false
#       register: public_ip
#       until: public_ip.status == 200
#       retries: 6
#       delay: 10
      

#     - set_stats:
#         data: 
#           kubernetes:
#             attributes: 
#               service_urls: 
#                 - "https://{{public_ip['json']['ip']}}:{{item}}"
#       loop: "{{ node_ports | dict2items }}"  
      

#     - set_fact:
#         attributes: 
#           service_urls: 
#           - "https://{{public_ip['json']['ip']}}:{{item}}"
#       loop: "{{ node_ports | dict2items }}"          
          
#     - name: Display the Dictionaries
#       debug: 
#         var: attributes
      

#     - debug:
#         var: item.value[0].item
#       loop: "{{ node_ports | dict2items }}"
  
