---
- hosts: master
  gather_facts: no
  tasks:
  
    - name: Get a list of services
      k8s_info:
        kind: Service
        namespace: "{{ item }}"
      register: k8s_services
      with_items:
        - "default"
        - "kubernetes-dashboard"

#     - name: "query node ports cluster names"
#       debug:
#         var: item
#       loop: "{{ k8s_services |  json_query('resources[?spec.type==`NodePort`].spec.ports[*].nodePort') }}"
#       register: node_ports


    - set_stats:
        data: 
          services: "{{k8s_services}}"
        

#     - name: Get the public IP address of the network.
#       uri:
#         url: https://api.ipify.org?format=json
#         method: Get
#       changed_when: false
#       register: public_ip
#       until: public_ip.status == 200
#       retries: 6
#       delay: 10
      

#     - set_stats:
#         data: 
#           kubernetes:
#             attributes: 
#               service_urls: 
#                 - "https://{{public_ip['json']['ip']}}:{{item}}"
#       loop: "{{ node_ports | dict2items }}"  
      

#     - set_fact:
#         attributes: 
#           service_urls: 
#           - "https://{{public_ip['json']['ip']}}:{{item}}"
#       loop: "{{ node_ports | dict2items }}"          
          
#     - name: Display the Dictionaries
#       debug: 
#         var: attributes
      

#     - debug:
#         var: item.value[0].item
#       loop: "{{ node_ports | dict2items }}"
  
