- hosts: all
  become: yes
  gather_facts: no
  tasks:       
            
    - include: ec2/ec2_mount.yaml
    - include: docker/install_docker.yaml
    - include: install_k8s_prerequisites.yaml
    
