- hosts: all
  become: yes
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:

    - apt:
        name:
        - lshw
        update_cache: yes

    - package:
        name:
        - jq
        state: present
      register: package_output

    - debug:
        var: package_output

    - snap:
        name:
          - jq
      when: package_output.rc =! 0

    - include: disk/mount.yaml
    - include: docker/install_docker.yaml
    - include: install_k8s_prerequisites.yaml
    
