- hosts: all
  become: yes
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:

    - name: Add the Kubernetes signing key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present
      register: task_result
      until: task_result.rc == 0
      retries: 10
      delay: 1

    - name: Add kubernetes
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present
      register: task_result
      until: task_result.rc == 0
      retries: 10
      delay: 1

    - name: Install Kubernetes Packages
      apt:
        pkg:
          - kubelet=1.20.2-00 
          - kubeadm=1.20.2-00 
          - kubectl=1.20.2-00

    - firewalld:
        port: "{{item}}"
        permanent: yes
        state: enabled
        immediate: yes
      with_items:
        - "8080/tcp"
        - "6443/tcp"
        - "10248-10255/tcp"
        - "30000-32767/tcp"
        - "2379-2380/tcp"

