- hosts: all
  become: yes
  tasks:       
  
    - pip:
        name:
            - openshift==0.11.0
            - kubernetes==11.0.0
      retries: 10
      delay: 1
      register: result
      until: result.rc == 0
            
    - include: ec2/ec2_mount.yaml
    - include: docker/install_docker.yaml
    - include: install_k8s_prerequisites.yaml
    
