- hosts: all
  become: yes
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:

    - apt:
        name:
        - lshw
        update_cache: yes

    - package:
        name:
        - jq
        state: present
      register: package_output
      ignore_errors: yes

    - snap:
        name:
          - jq
      when: not package_output['failed']

#    - include: disk/mount.yaml
#    - include: docker/install_docker.yaml
#    - include: install_k8s_prerequisites.yaml
    - include: disk/install_nfs-common.yaml
    
