- hosts: all
  become: yes
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:

    - apt:
        name:
        - lshw
        - snap
        update_cache: yes

    - snap:
        name:
          - jq

    - include: disk/mount.yaml
    - include: docker/install_docker.yaml
    - include: install_k8s_prerequisites.yaml
    
