- hosts: all
  become: yes
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:

    - apt:
        name:
        - lshw
        update_cache: yes


    - apt:
        name:
        - jq
        igonre_errors: yes
        register: apt_output

    - debug:
        var: apt_output

    - snap:
        name:
          - jq
      when: apt_output.rc =! 0

    - include: disk/mount.yaml
    - include: docker/install_docker.yaml
    - include: install_k8s_prerequisites.yaml
    
