- hosts: all
  become: yes
  tasks:

    - name: Add the Kubernetes signing key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add kubernetes
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present

    - name: Install Kubernetes Packages
      apt:
        pkg:
        - kubeadm
        - kubelet
        - kubectl
        - kubernetes-cni
        
#     - shell: firewall-cmd --permanent --zone=public --add-port="{{item}}"
#       with_items:
#         - "8080/tcp"
#         - "6443/tcp"
#         - "10250/tcp"
#         - "30000-32767/tcp"
#       register: firewall_out
      
#     - debug:
#         var: firewall_out

    - firewalld:
        port: "{{item}}"
        permanent: yes
        state: enabled
        immediate: yes
      with_items:
        - "8080/tcp"
        - "6443/tcp"
        - "10248-10255/tcp"
        - "30000-32767/tcp"
        - "2379-2380/tcp"


