---        
- hosts: master
  vars:
      ansible_python_interpreter: /usr/bin/python3
  tasks:         
    - name: join cmd
      become: yes
      shell: kubeadm token create --print-join-command
      register: k8_join_cmd  
      
    - name: Add join cmd to dummy host
      add_host:
        name:   "k8s_join_cmd_holder"
        cmd:  "{{ k8_join_cmd.stdout }}"
        
    - shell: iptables -D  INPUT -j REJECT --reject-with icmp-host-prohibited 
      become: yes
      ignore_errors: yes
      
    - shell: iptables -D  FORWARD -j REJECT --reject-with icmp-host-prohibited
      become: yes
      ignore_errors: yes
        
- hosts: all
  tasks:
  
     - name: Fetch the conf from master
       run_once: yes
       fetch: 
        src: ${HOME}/.kube/config 
        dest: /tmp/config
       when: "{{ inventory_hostname == 'master' }}"
       
     - file:
        path: ~/.kube
        state: directory
       when: "{{ inventory_hostname == 'worker' }}"
      
     - name: Copy conf to worker
       copy: 
        src: /tmp/config 
        dest: ${HOME}/.kube/config 
       when: "{{ inventory_hostname == 'worker' }}"
       
                
- hosts: worker
  gather_facts: no
  tasks:
    
    - shell: kubectl get nodes -o json #> /tmp/k8s_nods.json
      register: k8s_nods
      
    - debug:
        var: k8s_nods
      
#     - fetch: 
#         src: ${HOME}/.kube/config 
#         dest: /tmp/config
       
    - include_tasks: join_k8s_cluster_task.yaml
      
        
# - hosts: master
#   tasks: 

#     - name: get nodes
#       shell: kubectl get nodes
#       register: nodes_out
              
#     - name: print nodes
#       debug:
#         var: nodes_out
        
        
#     - name: get api key
#       shell: kubectl describe secret $(kubectl get secrets | grep default | cut -f1 -d ' ') | grep -E '^token' | cut -f2 -d':' | tr -d '\t'
#       register: api_key
              
#     - name: print api_key
#       debug:
#         var: api_key
