---        
- hosts: master
  gather_facts: no
  tasks:         
    - name: join cmd
      shell: kubeadm token create --print-join-command
      register: k8_join_cmd  
      
    - name: Add join cmd to dummy host
      add_host:
        name:   "k8s_join_cmd_holder"
        cmd:  "{{ k8_join_cmd.stdout }}"
        
        
- hosts: all
  tasks:
  
     - name: Fetch the conf from master
       run_once: yes
       fetch: 
        src: ${HOME}/.kube/config 
        dest: /tmp/config
       when: "{{ inventory_hostname == 'master' }}"
       
     - file:
        path: ~/.kube
        state: directory
       when: "{{ inventory_hostname == 'worker' }}"
      
     - name: Copy conf to worker
       copy: 
        src: /tmp/config 
        dest: ${HOME}/.kube/config 
       when: "{{ inventory_hostname == 'worker' }}"
        
                
- hosts: worker
  gather_facts: no
  tasks:
  
    - name: check if in cluster
      uri:
        url: http://localhost:10248/healthz
      register: url_command_result
      ignore_errors: True    
      
    - name: disable swap
      become: yes
      shell: swapoff -a    
      when: url_command_result.status != 200
      
      
    - name: Add the br_netfilter module
      become: yes    
      modprobe:
        name: br_netfilter
        state: present      
        
    - name: update sysctl param
      become: yes
      sysctl:
        name: "{{ item }}"
        value: 1
        state: present
        reload: yes
      with_items:
        - net.bridge.bridge-nf-call-ip6tables
        - net.ipv4.ip_forward
        
    - name: kubeadm reset -f
      shell: kubeadm reset -f
      become: yes     
      ignore_errors: True
        
    - name: join
      shell: "{{ hostvars['k8s_join_cmd_holder']['cmd'] }}"
      become: yes
      when: url_command_result.status != 200
      
