- hosts: master
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:

    - shell: helm delete flannel --namespace kube-flannel
    - shell: helm repo remove flannel
    - shell: kubectl label --overwrite ns kube-flannel pod-security.kubernetes.io/enforce-
    - shell: kubectl delete ns kube-flannel
