---        
- hosts: master
  gather_facts: no
  vars:
      ansible_python_interpreter: /usr/bin/python3
  tasks:

    - include: k8s-master.yaml
      register: task_output

    - debug:
        var: task_output

    - name: Failed reset cluster
      include: reset.yaml
      when: kuctl_weave_output.rc != 0

    - debug:
        var: kuctl_weave_output

    - include: k8s-master.yaml
      when: kuctl_weave_output.rc != 0

    - debug:
        var: kuctl_weave_output

    - fail:
        msg: Failed "{{ kuctl_weave_output }}"
      when: kuctl_weave_output.rc != 0
        
- hosts: master
  gather_facts: no
  tasks: 

    - name: get nodes
      shell: kubectl get nodes
      register: nodes_out

    - name: get api key
      shell: kubectl describe secret $(kubectl get secrets | grep default | cut -f1 -d ' ') | grep -E '^token' | cut -f2 -d':' | tr -d '\t'
      register: api_key
