controller:
  service:
    nodePorts:
      http: 32080
      https: 32443
      tcp:
        "8080": 32808
    type: NodePort
  extraArgs:
    default-ssl-certificate: "ingress-nginx/ingress-self-signed-tls"
ingressClassResource:
  default: true