
- shell: kubectl create role jenkins --verb=list,update --resource=workflows.argoproj.io  && kubectl create sa jenkins && kubectl create rolebinding jenkins --role=jenkins --serviceaccount=argo:jenkins
  ignore_errors: yes
  
- shell: SECRET=$(kubectl get sa jenkins -o=jsonpath='{.secrets[0].name}') && ARGO_TOKEN="Bearer $(kubectl get secret $SECRET -o=jsonpath='{.data.token}' | base64 --decode)" && echo $ARGO_TOKEN
  register: argo_token
